version: '3.8'

services:
  voiceattendance:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/voice_samples
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - voice_samples:/app/voice_samples
      - uploads:/app/uploads
      - data:/app/data
    secrets:
      - secret_key
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

secrets:
  secret_key:
    external: true

volumes:
  voice_samples:
  uploads:
  data:
