# Docker Compose for easy local testing
version: '3.8'

services:
  voice-attendance:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./voice_samples:/app/voice_samples
    environment:
      - FLASK_DEBUG=false
      - SECRET_KEY=your-secret-key-here
      - PORT=5000
    restart: unless-stopped

  # Optional: Add Redis for session storage in production
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
